### ISSUE TITLE
How is this different from what ddtrace does?

### ISSUE THREAD

**Issue by inikolaev** [florimondmanca/ddtrace-asgi#26]
I'm using `ddtrace` with FastAPI and I seem to get the similar information to what is being reported by this middleware. Does this middleware do anything else that official `ddtrace` does not or was it developed when there was no official support of ASGI available yet?

**Comment by florimondmanca** [comment]
Hi!

Can you share the metrics reported by ddtrace without this plugin?

At the time there was no mention of ASGI frameworks in ddtrace so I went with a new integration right away, but I’ll admit I never actually tried to run an ASGI app on vanilla ddtrace. :-) Perhaps you’re getting auto instrumentation from gunicorn or a similar piece?

**Comment by inikolaev** [comment]
Sure!

Well basically, I can see that `asgi.request` is being detected at an entry point for all my requests and then for each request I see the following tags:

```json
{
  "container_info": {},
  "duration": 18096862,
  "http": {
    "method": "POST",
    "status_code": 200,
    "url": "https://example.com"
  },
  "process_id": 1
}
```

I must admit I'm not super familiar with `ddtrace` and `uvicorn`.

Do you have an example what are you getting when using this middleware, maybe I'm missing some pieces?

I found this project when I was looking for the ways to group requests by route, because right now for a resource like `/users/{id}` I would get a separate resource filter entry for each user id, instead of a single entry per resource.

**Comment by inikolaev** [comment]
Ah, mystery solved! It turned out we actually use this middleware 😄

**Comment by florimondmanca** [comment]
Ah, so that explains why! 😉 Closing this then. :)

(Also, yes,  per-route submission of span isn’t supported currently. I don’t think that’s feasible at the raw ASGI layer so that might need tighter integration with Starlette/FastAPI. If you’d like to investigate feel free to report back!)
